"""
india_valuation.py
==================
Proprietary India-specific valuation adjustments for the NSE Equity Research
Report Generator.

Integrates with the existing equity_research/analysis/ pipeline. Call
IndiaValuationEngine(data, config).run() to get a full IndiaValuationResult
that can be included in the PDF report builder.
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)

# Hardcoded datasets for India specific factors
_PSU_TICKERS = {
    "ONGC", "NTPC", "COALINDIA", "POWERGRID", "NHPC", "SBI", "BANKBARODA", 
    "CANBK", "PNB", "INDIANB", "IOB", "MAHABANK", "UCOBANK", "CENTRALBK", 
    "UNIONBANK", "BEL", "HAL", "BHEL", "GAIL", "BPCL", "HINDPETRO", "IOC", 
    "OIL", "NMDC", "SAIL", "NBCC", "NLCINDIA", "IRFC", "RECLTD", "PFC", 
    "SJVN", "CONCOR", "IREDA", "RVNL", "HUDCO", "FACT", "MMTC", "NATIONALUM",
    "IRCTC", "IRCON", "ENGINERSIN", "COCHINSHIP", "GRSE", "MAZDOCK", "GICRE", 
    "NIACL", "LICI", "SBIN", "IDBI"
}

_GROUP_MAPPING = {
    # Tata
    "TCS": "Tata", "TATASTEEL": "Tata", "TATAPOWER": "Tata", "TATAMOTORS": "Tata", 
    "TATACONSUM": "Tata", "TATACOMM": "Tata", "TATAELXSI": "Tata", "TATACHEM": "Tata", 
    "TITAN": "Tata", "TRENT": "Tata", "VOLTAS": "Tata", "TATAINVEST": "Tata", 
    "TATATECH": "Tata", "TTML": "Tata",
    # Reliance
    "RELIANCE": "Reliance", "JIOFIN": "Reliance",
    # Adani
    "ADANIENT": "Adani", "ADANIPORTS": "Adani", "ADANIGREEN": "Adani", 
    "ADANIPOWER": "Adani", "ADANIENERGY": "Adani", "ATGL": "Adani",
    # Mahindra
    "M&M": "Mahindra", "TECHM": "Mahindra", "M&MFIN": "Mahindra",
    # Birla
    "GRASIM": "Birla", "ULTRACEMCO": "Birla", "ABCAPITAL": "Birla", 
    "ABFRL": "Birla", "ABSLAMC": "Birla", "HINDALCO": "Birla",
    # Bajaj
    "BAJFINANCE": "Bajaj", "BAJAJFINSV": "Bajaj", "BAJAJ-AUTO": "Bajaj", 
    "BAJAJHLDNG": "Bajaj",
    # Godrej
    "GODREJCP": "Godrej", "GODREJIND": "Godrej", "GODREJPROP": "Godrej",
    # JSW
    "JSWSTEEL": "JSW", "JSWENERGY": "JSW", "JSWINFRA": "JSW",
    # L&T
    "LT": "L&T", "LTTS": "L&T", "LTF": "L&T", "LTM": "L&T",
    # Vedanta
    "VEDL": "Vedanta", "HINDZINC": "Vedanta",
    # Hero
    "HEROMOTOCO": "Hero",
    # TVS
    "TVSMOTOR": "TVS",
    # Murugappa
    "TIINDIA": "Murugappa", "CARBORUNIV": "Murugappa", "CHOLAMANDALAM": "Murugappa"
}

# ─── DATA CLASSES ─────────────────────────────────────────────────────────────

@dataclass
class PromoterProfile:
    """Sourced from NSE/BSE shareholding pattern disclosures."""
    promoter_holding_pct: float      # e.g. 68.0 = 68%
    promoter_pledge_pct:  float      # pledged as % of promoter holding
    has_qualified_audit:  bool       # True = clean audit opinion
    related_party_pct:    float      # related-party revenue as % of total revenue

@dataclass
class IndiaValuationInputs:
    """All inputs the engine needs, beyond the standard DCF config."""
    # From yfinance / screener
    ticker:              str
    sector:              str              # e.g. "Financial Services", "Information Technology"
    industry:            str              # finer grain, e.g. "Banks", "IT Consulting"
    is_psu:              bool             # True if Govt of India is promoter
    business_group:      Optional[str]    # e.g. "Tata", "Adani", "Reliance", or None
    is_holding_company:  bool             # True for Bajaj Holdings, Tata Investment, etc.

    # Governance data (defaults used when unavailable via yfinance)
    promoter:            PromoterProfile

    # Financials (latest FY)
    net_income:          float
    ebitda:              float
    cfo:                 float            # Cash flow from operations
    total_assets:        float
    total_assets_prev:   float
    current_assets:      float
    current_assets_prev: float
    current_liabs:       float
    current_liabs_prev:  float

    # Derived from intrinsic DCF/ER/RI models
    dcf_equity_value_per_share: float
    dcf_wacc:            float
    dcf_terminal_growth: float
    
    # Current Market Data
    current_price:       float
    shares_outstanding:  float
    net_debt:            float            # total_debt - cash_and_equivalents


@dataclass
class IndiaValuationResult:
    """The final adjustments generated by the engine."""
    
    # 1. Sector Routing
    primary_multiple: str
    sector_note: str
    
    # 2. PSU Discount
    is_psu: bool
    psu_discount_pct: float
    
    # 3. Promoter Quality
    promoter_score: float                # 0 to 100
    promoter_premium_pct: float          # e.g. 0.05 for +5%
    promoter_flags: list[str]            # Warnings if pledge > 25% or related party > 10%
    
    # 4. Group Adjustment
    group_adjustment_pct: float
    
    # 5. Earnings Quality
    earnings_quality_score: float        # 0 to 100
    accruals_ratio: float
    cfo_ebitda_ratio: float
    earnings_quality_flags: list[str]
    
    # 6. Reverse DCF
    implied_revenue_cagr: float
    dcf_vs_price_gap_pct: float
    
    # 7. Blended Valuation
    adjusted_dcf_value: float            # DCF applied with structural discounts/premiums
    blended_value: float                 # Final triangulated price
    blended_upside_pct: float
    
    narrative_bullets: list[str]         # Ready for PDF renderer
    
    # Guardrail check
    diverges_materially: bool


class IndiaValuationEngine:
    def __init__(self, inputs: IndiaValuationInputs):
        self.inputs = inputs
        self.result = IndiaValuationResult(
            primary_multiple="", sector_note="", is_psu=False, psu_discount_pct=0.0,
            promoter_score=0.0, promoter_premium_pct=0.0, promoter_flags=[],
            group_adjustment_pct=0.0, earnings_quality_score=0.0,
            accruals_ratio=0.0, cfo_ebitda_ratio=0.0, earnings_quality_flags=[],
            implied_revenue_cagr=0.0, dcf_vs_price_gap_pct=0.0,
            adjusted_dcf_value=0.0, blended_value=0.0, blended_upside_pct=0.0,
            narrative_bullets=[], diverges_materially=False
        )

    def _get_sector_config(self) -> None:
        """Route to appropriate multiples based on sector/industry."""
        sec = (self.inputs.sector or "").lower()
        ind = (self.inputs.industry or "").lower()
        
        if "bank" in ind or "financial" in sec:
            self.result.primary_multiple = "P/B"
            self.result.sector_note = "Financials are valued using P/B spreads and excess return."
        elif "information technology" in sec or "software" in ind:
            self.result.primary_multiple = "EV/EBITDA"
            self.result.sector_note = "IT sector relies on EV/EBITDA to normalize cash conversion."
        elif "real estate" in sec:
            self.result.primary_multiple = "P/NAV"
            self.result.sector_note = "Real estate primarily valued on Price to Net Asset Value."
        else:
            self.result.primary_multiple = "P/E"
            self.result.sector_note = "Standard P/E multiple used as primary relative metric."

    def _psu_discount(self) -> None:
        """Apply structural discount for government-controlled entities."""
        self.result.is_psu = self.inputs.is_psu
        if self.inputs.is_psu:
            self.result.psu_discount_pct = 0.20
            self.result.narrative_bullets.append("Applies a 20% structural PSU discount to account for capital allocation risk.")
        else:
            self.result.psu_discount_pct = 0.0

    def _promoter_score(self) -> None:
        """Evaluate governance using shareholding parameters."""
        p = self.inputs.promoter
        score = 75.0  # Base neutral score
        premium = 0.0
        
        if p.promoter_holding_pct > 50:
            score += 10
            premium += 0.05
            
        if p.promoter_pledge_pct > 25:
            score -= 30
            premium -= 0.15
            self.result.promoter_flags.append(f"High promoter pledge ({p.promoter_pledge_pct}%)")
        elif p.promoter_pledge_pct > 0:
            score -= 10
            premium -= 0.05
            
        if p.related_party_pct > 10:
            score -= 20
            premium -= 0.10
            self.result.promoter_flags.append(f"High related-party transactions ({p.related_party_pct}%)")
            
        if not p.has_qualified_audit:
            score -= 20
            premium -= 0.10
            self.result.promoter_flags.append("Qualified audit opinion")
            
        # If it's the exact default safe profile, score is 75 (neutral)
        if p.promoter_holding_pct == 50.0 and p.promoter_pledge_pct == 0.0 and p.related_party_pct == 0.0 and p.has_qualified_audit:
            self.result.promoter_flags.append("Using default governance assumptions (data unavailable)")
            premium = 0.0
            score = 75.0
            
        self.result.promoter_score = max(0.0, min(100.0, score))
        self.result.promoter_premium_pct = premium

    def _group_adjustment(self) -> None:
        """Apply premium/discount based on business group reputation."""
        grp = self.inputs.business_group
        adj = 0.0
        
        if grp == "Tata":
            adj = 0.10
            self.result.narrative_bullets.append("10% valuation premium applied for Tata group (governance & capital access).")
        elif grp in ["HDFC", "Infosys"]:
            adj = 0.05
        elif grp == "Adani":
            adj = -0.10
            self.result.narrative_bullets.append("10% valuation discount applied for Adani group (higher leverage & governance scrutiny).")
        elif grp == "Vedanta":
            adj = -0.15
            self.result.narrative_bullets.append("15% valuation discount applied for Vedanta group (capital allocation concerns).")
            
        if self.inputs.is_holding_company:
            adj -= 0.30
            self.result.narrative_bullets.append("30% holding company discount applied to intrinsic value.")
            
        self.result.group_adjustment_pct = adj

    def _earnings_quality(self) -> None:
        """Assess earnings quality using Sloan accruals and cash conversion."""
        avg_assets = (self.inputs.total_assets + self.inputs.total_assets_prev) / 2
        if avg_assets > 0:
            # Simple accruals = Net Income - CFO
            accruals = self.inputs.net_income - self.inputs.cfo
            self.result.accruals_ratio = accruals / avg_assets
        else:
            self.result.accruals_ratio = 0.0
            
        if self.inputs.ebitda > 0:
            self.result.cfo_ebitda_ratio = self.inputs.cfo / self.inputs.ebitda
        else:
            self.result.cfo_ebitda_ratio = 0.0
            
        score = 80.0
        if self.result.accruals_ratio > 0.05:
            score -= 20
            self.result.earnings_quality_flags.append("High positive accruals (potential earnings management)")
        if self.result.cfo_ebitda_ratio < 0.5 and self.inputs.ebitda > 0:
            score -= 30
            self.result.earnings_quality_flags.append("Poor cash conversion (CFO/EBITDA < 50%)")
            
        self.result.earnings_quality_score = max(0.0, min(100.0, score))

    def _reverse_dcf(self) -> None:
        """Calculate the implied growth rate priced into the current stock price."""
        price = self.inputs.current_price
        dcf_val = self.inputs.dcf_equity_value_per_share
        
        if dcf_val > 0 and price > 0:
            self.result.dcf_vs_price_gap_pct = (dcf_val - price) / price
            
            # Simple heuristic for implied CAGR based on price vs DCF
            # E.g., if price is 50% higher than DCF (which assumes 8% growth),
            # the implied growth is roughly 8% + 5% = 13%
            implied_g = self.inputs.dcf_terminal_growth + (math.log(price / dcf_val) / 10.0)
            self.result.implied_revenue_cagr = max(-0.60, min(0.60, implied_g))
        else:
            self.result.dcf_vs_price_gap_pct = 0.0
            self.result.implied_revenue_cagr = self.inputs.dcf_terminal_growth

    def _blended_value(self) -> None:
        """Combine intrinsic DCF with India-specific premiums/discounts."""
        base_dcf = self.inputs.dcf_equity_value_per_share
        
        # Apply structured discounts and premiums
        total_adj_factor = 1.0 - self.result.psu_discount_pct + self.result.promoter_premium_pct + self.result.group_adjustment_pct
        
        self.result.adjusted_dcf_value = max(0.0, base_dcf * total_adj_factor)
        
        # For this engine, we'll just use the adjusted DCF as the blended value
        # if relative valuation isn't explicitly passed in as an input.
        self.result.blended_value = self.result.adjusted_dcf_value
        
        if self.inputs.current_price > 0:
            self.result.blended_upside_pct = (self.result.blended_value - self.inputs.current_price) / self.inputs.current_price
        else:
            self.result.blended_upside_pct = 0.0
            
        # Guardrail check
        if self.inputs.current_price > 0:
            ratio = self.result.blended_value / self.inputs.current_price
            if ratio < 0.1 or ratio > 10.0:
                self.result.diverges_materially = True

    def run(self) -> IndiaValuationResult:
        """Execute all valuation layers."""
        self._get_sector_config()
        self._psu_discount()
        self._promoter_score()
        self._group_adjustment()
        self._earnings_quality()
        self._reverse_dcf()
        self._blended_value()
        
        # Add summary bullets
        if self.result.earnings_quality_score < 50:
            self.result.narrative_bullets.append("Low earnings quality detected; reliance on cash flows recommended over net income.")
        if self.result.implied_revenue_cagr > 0.20:
            self.result.narrative_bullets.append(f"Current price implies aggressive {self.result.implied_revenue_cagr:.1%} long-term growth rate.")
            
        return self.result

def build_india_inputs(
    ticker: str,
    profile: dict,
    financials: dict[str, pd.DataFrame],
    dcf_equity_value_per_share: float,
    dcf_wacc: float,
    dcf_terminal_growth: float
) -> IndiaValuationInputs:
    """Helper to construct inputs from existing pipeline data."""
    
    ticker_base = ticker.replace(".NS", "")
    is_psu = ticker_base in _PSU_TICKERS
    group = _GROUP_MAPPING.get(ticker_base)
    
    ind = (profile.get("industry") or "").lower()
    is_holding = "holding" in ind or profile.get("long_name", "").lower().endswith("holdings ltd.")
    
    # Financial extraction
    inc = financials.get("income", pd.DataFrame())
    bal = financials.get("balance_sheet", pd.DataFrame())
    cf = financials.get("cash_flow", pd.DataFrame())
    
    def _latest(df, col):
        if df.empty or col not in df.columns:
            return 0.0
        val = df[col].dropna()
        if val.empty:
            return 0.0
        return float(val.iloc[-1])
        
    def _prev(df, col):
        if df.empty or col not in df.columns:
            return 0.0
        val = df[col].dropna()
        if len(val) < 2:
            return 0.0
        return float(val.iloc[-2])
    
    net_income = _latest(inc, "net_income")
    ebitda = _latest(inc, "ebitda")
    cfo = _latest(cf, "operating_cash_flow")
    
    total_assets = _latest(bal, "total_assets")
    total_assets_prev = _prev(bal, "total_assets")
    current_assets = _latest(bal, "current_assets")
    current_assets_prev = _prev(bal, "current_assets")
    current_liabs = _latest(bal, "current_liabilities")
    current_liabs_prev = _prev(bal, "current_liabilities")
    
    net_debt = _latest(bal, "total_debt") - _latest(bal, "cash_and_equivalents")
    
    # Safe defaults for promoter since yfinance doesn't provide it
    promoter = PromoterProfile(
        promoter_holding_pct=50.0,
        promoter_pledge_pct=0.0,
        has_qualified_audit=True,
        related_party_pct=0.0
    )
    
    return IndiaValuationInputs(
        ticker=ticker,
        sector=profile.get("sector", ""),
        industry=profile.get("industry", ""),
        is_psu=is_psu,
        business_group=group,
        is_holding_company=is_holding,
        promoter=promoter,
        net_income=net_income,
        ebitda=ebitda,
        cfo=cfo,
        total_assets=total_assets,
        total_assets_prev=total_assets_prev,
        current_assets=current_assets,
        current_assets_prev=current_assets_prev,
        current_liabs=current_liabs,
        current_liabs_prev=current_liabs_prev,
        dcf_equity_value_per_share=dcf_equity_value_per_share,
        dcf_wacc=dcf_wacc,
        dcf_terminal_growth=dcf_terminal_growth,
        current_price=profile.get("current_price", 0.0) or 0.0,
        shares_outstanding=profile.get("shares_outstanding", 0.0) or 0.0,
        net_debt=net_debt
    )
