import pandas as pd
import numpy as np
import sqlite3
import os

def calculate_indicators(df):
    # Ensure sorted by time
    df = df.sort_values('timestamp').reset_index(drop=True)
    
    # 1. RSI (14)
    delta = df['close'].diff()
    gain = delta.where(delta > 0, 0).ewm(alpha=1/14, adjust=False).mean()
    loss = -delta.where(delta < 0, 0).ewm(alpha=1/14, adjust=False).mean()
    rs = gain / loss
    df['rsi'] = 100 - (100 / (1 + rs))
    
    # 2. MACD (12, 26, 9)
    exp1 = df['close'].ewm(span=12, adjust=False).mean()
    exp2 = df['close'].ewm(span=26, adjust=False).mean()
    df['macd'] = exp1 - exp2
    df['macd_signal'] = df['macd'].ewm(span=9, adjust=False).mean()
    
    # 3. Bollinger Bands (20, 2)
    rolling_mean = df['close'].rolling(window=20).mean()
    rolling_std = df['close'].rolling(window=20).std()
    df['bb_upper'] = rolling_mean + (rolling_std * 2)
    df['bb_lower'] = rolling_mean - (rolling_std * 2)
    
    # 4. ATR Proxy (14)
    # True Range in simple proxy is abs(High - Low) or just abs(Close - PrevClose) for simple candles
    # Let's use High-Low since we have OHLC
    # tr = df['high'] - df['low'] # Classic TR 1
    # Actually, proper TR takes previous close into account. 
    # Let's stick to the strategy.py implementation to be consistent?
    # strategy.py used: tr = abs(df['close'] - df['close'].shift(1))
    # We should match that for consistency.
    tr = abs(df['close'] - df['close'].shift(1))
    df['atr'] = tr.ewm(alpha=1/14, adjust=False).mean()
    
    # 5. Fixed/Bridged Values
    df['vix'] = 11.0
    df['call_delta'] = 0.5
    df['put_delta'] = -0.5
    df['spot_price'] = df['close']
    
    return df

def generate_targets(df):
    """
    Triple Barrier Method:
    Barrier: +0.10%
    Horizon: 20 candles
    """
    targets = []
    threshold = 0.0010  # 0.10%
    horizon = 20
    
    for i in range(len(df)):
        # End of window
        end_idx = min(i + horizon, len(df))
        current_price = df['close'].iloc[i]
        
        # Look ahead
        future_prices = df['close'].iloc[i+1 : end_idx]
        
        if len(future_prices) == 0:
            targets.append(0)
            continue
            
        # Check Upside Barrier
        max_price = future_prices.max()
        gain = (max_price - current_price) / current_price
        
        if gain >= threshold:
            targets.append(1) # Hit Profit Target
        else:
            targets.append(0) # Time out or Stop Loss (implicit 0)
            
    df['target'] = targets
    
    # Drop the last 'horizon' rows as their targets are incomplete/not full horizon
    # Although for appending, maybe we keep them as 0? 
    # Standard practice is to drop undefined targets.
    df = df.iloc[:-horizon].copy()
    
    return df

def main():
    input_file = "ready_for_training.csv"
    db_path = "quant_lab.db"
    
    if not os.path.exists(input_file):
        print(f"[ERROR] {input_file} not found.")
        return
        
    print(f"[INFO] Processing {input_file}...")
    df = pd.read_csv(input_file)
    
    # 1. Feature Engineering
    df = calculate_indicators(df)
    
    # Drop NaNs generated by indicators (rolling windows)
    original_len = len(df)
    df.dropna(inplace=True)
    print(f"[INFO] Indicator Warm-up Dropped: {original_len - len(df)} rows")
    
    # 2. Target Generation
    df = generate_targets(df)
    print(f"[INFO] Post-Target Generation Rows: {len(df)}")
    
    # 3. Validation
    # Check Class Balance
    buy_signals = df['target'].sum()
    print(f"[INFO] New Buy Signals: {buy_signals} ({buy_signals/len(df)*100:.2f}%)")
    
    # 4. Merge to Database
    # Schema: timestamp, spot_price, vix, call_delta, put_delta, rsi, macd, macd_signal, bb_upper, bb_lower, atr, target
    cols_to_save = [
        'timestamp', 'spot_price', 'vix', 'call_delta', 'put_delta',
        'rsi', 'macd', 'macd_signal', 'bb_upper', 'bb_lower', 'atr', 'target'
    ]
    
    final_df = df[cols_to_save]
    
    try:
        conn = sqlite3.connect(db_path)
        final_df.to_sql('smart_training_data', conn, if_exists='append', index=False)
        conn.close()
        print(f"\n[SUCCESS] Successfully added {len(final_df)} real-world rows to 'smart_training_data'.")
    except Exception as e:
        print(f"[ERROR] Database Write Failed: {e}")

if __name__ == "__main__":
    main()
